### ISSUE TITLE
0"000.000| BUG in low_init(): [main] Cobalt core not enabled in kernel

### ISSUE THREAD

**Issue by wangfeiren** [thanhtam-h/rpi23-4.9.80-xeno3#1]
I installed xenomai according to this script (https://github.com/thanhtam-h/rpi23-4.9.80-xeno3/tree/master/scripts), but when I run "sudo /usr/xenomai/bin/latency", I get this: "0"000.000| BUG in low_init(): [main] Cobalt core not enabled in kernel"

**Comment by thanhtam-h** [comment]
How about prebuilt package?

**Comment by littleggghost** [comment]
Hi, @thanhtam-h 
I use the prebuilt package and still get this same error. Is there something wrong? I'm sure that I follow the steps in Readme.md file.

**Comment by littleggghost** [comment]
Hi, @wangfeiren 
Have you fixed this problem? How?

**Comment by littleggghost** [comment]
Use Raspbian will fix this problem.
