### ISSUE TITLE
Prebuilt didnt work

### ISSUE THREAD

**Issue by davoodmoradi** [thanhtam-h/rpi23-4.9.80-xeno3#2]
i started from scratch with rasbian Streach and followed the prebuilt step by step. but it crashed at last step.
sudo make -i modules_prepare
i am using the new RPi 3 B+
any idea what went wrong?

**Comment by thanhtam-h** [comment]
This is an issue of kernel header and still an unknown issue. However, just ignore this error message, this kernel header work well. After completing, you may try to build any simple module for testing.
If later you found other problems with this header just let me know.

**Comment by davoodmoradi** [comment]
Thanks Tam,

I tested, it works.

Cheers

Davood
