### ISSUE TITLE
Which version of Ubuntu matches for rpi 3b+?

### ISSUE THREAD

**Issue by littleggghost** [thanhtam-h/rpi23-4.9.80-xeno3#3]
Hi, @thanhtam-h 
I read your blog a lot and thanks for your sharing! Here I have a quite "stupid" question:
Which version of ubuntu is running on rpi? Ubuntu mate ,ubuntu16.04 or raspbian? What you says in this repository is to install the patched real-time kernel, but I want to know the original ubuntu version before patched.
I have new rpi without any system on it yet (the SD card is blank), what should I install first? Is there any reference link I can check?
As far as I know, the first step is to download the right .img file for flashing the SD card. 
Hope for your reply!

**Comment by thanhtam-h** [comment]
Raspbian is preferred. However Lubuntu mate or Ubuntu mate also work well.
