### ISSUE TITLE
File "pinctrl-bcm2835.c" not found in scrips?

### ISSUE THREAD

**Issue by littleggghost** [thanhtam-h/rpi23-4.9.80-xeno3#5]
![not found](https://user-images.githubusercontent.com/5058791/50684057-34742b00-104f-11e9-8bf4-0864cdadc63c.PNG)
Hi, @thanhtam-h 
As the pictures shows, there is an conflict between your [blog](http://www.simplerobot.net/2018/06/build-realtime-xenomai-3-kernel-for_3.html) and repository. The "pinctrl-bcm2835.c" file is not exist!
Which is right? Your blog or repository?

**Comment by thanhtam-h** [comment]
This step can be ignored, it is necessary for rpi0,1 build only. I will fix guide
